config/routes.rb
Lkksswin::Application.routes.draw do

  get "report_gazcontrols/show"
  resources :report_gazcontrols

  get "report_controls/show"
  resources :report_controls

  get "costs/end_price"

  resources :cost_inputs

  resources :cost_menus

  resources :xls

  resources :menu_reports

  devise_for :users

  devise_for :models
  match '/certificates/new' => 'certificates#new'
  resources :costs
  post "certificates/cost"
  post "loadcertifics/new"
  post "data_pipes/new"
  resources :magazines
  get "magazines/show"
  get "journal/index"
  post "journal/index"
  get "journal/link"
  resources :type_pipe_installation_sites
  post "loadcertifics/download"
  post "loadcertifics/undownload"
  get "loadcertifics/download"
  get "loadcertifics/undownload"
  resources :loadcertifics
  get "load/index"
  get "load/rem"
  get "downloads/rem"
  resources :reports
  resources :results
  resources :support_documents
  resources :certificates
  resources :passports
  resources :passport_pipes
  resources :pipes
  resources :installation_sites
  resources :conclusions
  resources :data_pipes
  resources :type_pipes
  resources :documents
  resources :sizes_pipes
  resources :instrumentations
  resources :represent_trans
  resources :represent_hosts
  resources :ties
  resources :gosts
  resources :delegates
  resources :manufacturs
  get "guide/index"
  get "main/index"
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'loadcertifics#new'

end

app/models/akt.rb
class Akt < ActiveRecord::Base
  belongs_to :zavod
  belongs_to :tipdef
  belongs_to :ntrub
  belongs_to :konstr  
end

app/models/cost.rb
class Cost < ActiveRecord::Base
end

app/models/cost_menu.rb
class CostMenu < ActiveRecord::Base
end

app/models/delegate.rb
class Delegate < ActiveRecord::Base
  has_many :certificates
end

app/models/document.rb
class Document < ActiveRecord::Base
  has_many :sizes_pipes
  has_many :conclusion
end

app/models/download.rb
class Download < ActiveRecord::Base
  attr_accessible :name, :link, :remote_link_url
  mount_uploader :link, LinkUploader
end

app/models/gost.rb
class Gost < ActiveRecord::Base
  has_many :certificates
end

app/models/konstr.rb
class Konstr < ActiveRecord::Base
  has_many :akts
end

app/models/magazine.rb
class Magazine < ActiveRecord::Base
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/ntrub.rb
class Ntrub < ActiveRecord::Base
  has_many :akts
end

app/models/passport.rb
class Passport < ActiveRecord::Base
  has_many :pipes, :through => :passport_pipes
end

app/models/pipe.rb
class Pipe < ActiveRecord::Base
  has_many :passports, :through => :passport_pipes
  belongs_to :data_pipe
  belongs_to :result
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :certificate
  belongs_to :pipe, :dependent => :delete
end

app/models/support_document.rb
class SupportDocument < ActiveRecord::Base
  has_many :certificates
end

app/models/terra.rb
class Terra < ActiveRecord::Base
end

app/models/tipdef.rb
class Tipdef < ActiveRecord::Base
  has_many :akts
end

app/models/ty.rb
class Ty < ActiveRecord::Base
  has_many :certificates
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/xl.rb
class Xl < ActiveRecord::Base
end

app/models/zavod.rb
class Zavod < ActiveRecord::Base
  has_many :akts
end

app/controllers/support_documents_controller.rb
class SupportDocumentsController < InheritedResources::Base
end

app/helpers/support_documents_helper.rb
module SupportDocumentsHelper
end

app/views/support_documents/_form.html.erb
<%= form_for(@support_document) do |f| %>
  <% if @support_document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@support_document.errors.count, "error") %> prohibited this support_document from being saved:</h2>

      <ul>
      <% @support_document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :name_product %><br />
    <%= f.text_field :name_product %>
  </div>
  <div class="field">
    <%= f.label :date_issue %><br />
    <%= f.datetime_select :date_issue %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/support_documents/edit.html.erb
<h1>Editing support_document</h1>

<%= render 'form' %>

<%= link_to 'Show', @support_document %> |
<%= link_to 'Back', support_documents_path %>

app/views/support_documents/index.html.erb
<h1>Listing support_documents</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Name product</th>
    <th>Date issue</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @support_documents.each do |support_document| %>
  <tr>
    <td><%= support_document.name %></td>
    <td><%= support_document.name_product %></td>
    <td><%= support_document.date_issue %></td>
    <td><%= link_to 'Show', support_document %></td>
    <td><%= link_to 'Edit', edit_support_document_path(support_document) %></td>
    <td><%= link_to 'Destroy', support_document, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Support document', new_support_document_path %>

app/views/support_documents/new.html.erb
<h1>New support_document</h1>

<%= render 'form' %>

<%= link_to 'Back', support_documents_path %>

app/views/support_documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @support_document.name %>
</p>

<p>
  <b>Name product:</b>
  <%= @support_document.name_product %>
</p>

<p>
  <b>Date issue:</b>
  <%= @support_document.date_issue %>
</p>


<%= link_to 'Edit', edit_support_document_path(@support_document) %> |
<%= link_to 'Back', support_documents_path %>