config/routes.rb
Lkksswin::Application.routes.draw do

  get "report_gazcontrols/show"
  resources :report_gazcontrols

  get "report_controls/show"
  resources :report_controls

  get "costs/end_price"

  resources :cost_inputs

  resources :cost_menus

  resources :xls

  resources :menu_reports

  devise_for :users

  devise_for :models
  match '/certificates/new' => 'certificates#new'
  resources :costs
  post "certificates/cost"
  post "loadcertifics/new"
  post "data_pipes/new"
  resources :magazines
  get "magazines/show"
  get "journal/index"
  post "journal/index"
  get "journal/link"
  resources :type_pipe_installation_sites
  post "loadcertifics/download"
  post "loadcertifics/undownload"
  get "loadcertifics/download"
  get "loadcertifics/undownload"
  resources :loadcertifics
  get "load/index"
  get "load/rem"
  get "downloads/rem"
  resources :reports
  resources :results
  resources :support_documents
  resources :certificates
  resources :passports
  resources :passport_pipes
  resources :pipes
  resources :installation_sites
  resources :conclusions
  resources :data_pipes
  resources :type_pipes
  resources :documents
  resources :sizes_pipes
  resources :instrumentations
  resources :represent_trans
  resources :represent_hosts
  resources :ties
  resources :gosts
  resources :delegates
  resources :manufacturs
  get "guide/index"
  get "main/index"
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'loadcertifics#new'

end

app/models/akt.rb
class Akt < ActiveRecord::Base
  belongs_to :zavod
  belongs_to :tipdef
  belongs_to :ntrub
  belongs_to :konstr  
end

app/models/cost.rb
class Cost < ActiveRecord::Base
end

app/models/cost_input.rb
class CostInput < ActiveRecord::Base
end

app/models/cost_menu.rb
class CostMenu < ActiveRecord::Base
end

app/models/delegate.rb
class Delegate < ActiveRecord::Base
  has_many :certificates
end

app/models/document.rb
class Document < ActiveRecord::Base
  has_many :sizes_pipes
  has_many :conclusion
end

app/models/download.rb
class Download < ActiveRecord::Base
  attr_accessible :name, :link, :remote_link_url
  mount_uploader :link, LinkUploader
end

app/models/gost.rb
class Gost < ActiveRecord::Base
  has_many :certificates
end

app/models/konstr.rb
class Konstr < ActiveRecord::Base
  has_many :akts
end

app/models/magazine.rb
class Magazine < ActiveRecord::Base
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/ntrub.rb
class Ntrub < ActiveRecord::Base
  has_many :akts
end

app/models/passport.rb
class Passport < ActiveRecord::Base
  has_many :pipes, :through => :passport_pipes
end

app/models/pipe.rb
class Pipe < ActiveRecord::Base
  has_many :passports, :through => :passport_pipes
  belongs_to :data_pipe
  belongs_to :result
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :certificate
  belongs_to :pipe, :dependent => :delete
end

app/models/terra.rb
class Terra < ActiveRecord::Base
end

app/models/tipdef.rb
class Tipdef < ActiveRecord::Base
  has_many :akts
end

app/models/ty.rb
class Ty < ActiveRecord::Base
  has_many :certificates
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/xl.rb
class Xl < ActiveRecord::Base
end

app/models/zavod.rb
class Zavod < ActiveRecord::Base
  has_many :akts
end

app/controllers/cost_inputs_controller.rb
class CostInputsController < InheritedResources::Base
  def show
    redirect_to :action => 'new', :controller => 'loadcertifics'
  end
end

app/helpers/cost_inputs_helper.rb
module CostInputsHelper
end

app/views/cost_inputs/_form.html.erb
<%= simple_form_for(@cost_input) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :hour, :label => 'один час работы' %>
    <%= f.input :material, :label => 'один кв. мм.' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'сохранить изменения' %>
  </div>
<% end %>

app/views/cost_inputs/edit.html.erb
<h1>изменить стоимости</h1>

<%= render 'form' %>

<% link_to 'Show', @cost_input %>
<%= button_to 'назад', new_cost_menu_path %>

app/views/cost_inputs/index.html.erb
<h1>Listing cost_inputs</h1>

<table>
  <tr>
    <th>Hour</th>
    <th>Material</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cost_inputs.each do |cost_input| %>
  <tr>
    <td><%= cost_input.hour %></td>
    <td><%= cost_input.material %></td>
    <td><%= link_to 'Show', cost_input %></td>
    <td><%= link_to 'Edit', edit_cost_input_path(cost_input) %></td>
    <td><%= link_to 'Destroy', cost_input, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cost input', new_cost_input_path %>

app/views/cost_inputs/new.html.erb
<h1>New cost_input</h1>

<%= render 'form' %>

<%= link_to 'Back', cost_inputs_path %>

app/views/cost_inputs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Hour:</b>
  <%= @cost_input.hour %>
</p>

<p>
  <b>Material:</b>
  <%= @cost_input.material %>
</p>


<%= link_to 'Edit', edit_cost_input_path(@cost_input) %> |
<%= link_to 'Back', cost_inputs_path %>