config/routes.rb
Lkksswin::Application.routes.draw do

  get "report_gazcontrols/show"
  resources :report_gazcontrols

  get "report_controls/show"
  resources :report_controls

  get "costs/end_price"

  resources :cost_inputs

  resources :cost_menus

  resources :xls

  resources :menu_reports

  devise_for :users

  devise_for :models
  match '/certificates/new' => 'certificates#new'
  resources :costs
  post "certificates/cost"
  post "loadcertifics/new"
  post "data_pipes/new"
  resources :magazines
  get "magazines/show"
  get "journal/index"
  post "journal/index"
  get "journal/link"
  resources :type_pipe_installation_sites
  post "loadcertifics/download"
  post "loadcertifics/undownload"
  get "loadcertifics/download"
  get "loadcertifics/undownload"
  resources :loadcertifics
  get "load/index"
  get "load/rem"
  get "downloads/rem"
  resources :reports
  resources :results
  resources :support_documents
  resources :certificates
  resources :passports
  resources :passport_pipes
  resources :pipes
  resources :installation_sites
  resources :conclusions
  resources :data_pipes
  resources :type_pipes
  resources :documents
  resources :sizes_pipes
  resources :instrumentations
  resources :represent_trans
  resources :represent_hosts
  resources :ties
  resources :gosts
  resources :delegates
  resources :manufacturs
  get "guide/index"
  get "main/index"
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'loadcertifics#new'

end

app/models/akt.rb
class Akt < ActiveRecord::Base
  belongs_to :zavod
  belongs_to :tipdef
  belongs_to :ntrub
  belongs_to :konstr  
end

app/models/cost.rb
class Cost < ActiveRecord::Base
end

app/models/cost_menu.rb
class CostMenu < ActiveRecord::Base
end

app/models/delegate.rb
class Delegate < ActiveRecord::Base
  has_many :certificates
end

app/models/document.rb
class Document < ActiveRecord::Base
  has_many :sizes_pipes
  has_many :conclusion
end

app/models/download.rb
class Download < ActiveRecord::Base
  attr_accessible :name, :link, :remote_link_url
  mount_uploader :link, LinkUploader
end

app/models/gost.rb
class Gost < ActiveRecord::Base
  has_many :certificates
end

app/models/konstr.rb
class Konstr < ActiveRecord::Base
  has_many :akts
end

app/models/magazine.rb
class Magazine < ActiveRecord::Base
end

app/models/manufactur.rb
class Manufactur < ActiveRecord::Base
  has_many :certificates
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/ntrub.rb
class Ntrub < ActiveRecord::Base
  has_many :akts
end

app/models/passport.rb
class Passport < ActiveRecord::Base
  has_many :pipes, :through => :passport_pipes
end

app/models/pipe.rb
class Pipe < ActiveRecord::Base
  has_many :passports, :through => :passport_pipes
  belongs_to :data_pipe
  belongs_to :result
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :certificate
  belongs_to :pipe, :dependent => :delete
end

app/models/terra.rb
class Terra < ActiveRecord::Base
end

app/models/tipdef.rb
class Tipdef < ActiveRecord::Base
  has_many :akts
end

app/models/ty.rb
class Ty < ActiveRecord::Base
  has_many :certificates
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/xl.rb
class Xl < ActiveRecord::Base
end

app/models/zavod.rb
class Zavod < ActiveRecord::Base
  has_many :akts
end

app/controllers/manufacturs_controller.rb
class ManufactursController < InheritedResources::Base
end

app/helpers/manufacturs_helper.rb
module ManufactursHelper
end

app/views/manufacturs/_form.html.erb
<%= form_for(@manufactur) do |f| %>
  <% if @manufactur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manufactur.errors.count, "error") %> prohibited this manufactur from being saved:</h2>

      <ul>
      <% @manufactur.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table>
  	<tr>
  <div class="field">
    <td ><%= f.label 'название' %></td>
    <td ><%= f.text_field :name %></td>
  </div>
  </tr>
  <tr>
  <div class="field">
    <td><%= f.label 'адресс' %></td>
    <td><%= f.text_field :address %></td>
  </div>
  <tr>
  <div class="field">
    <td><%= f.label 'телефон' %></td>
    <td><%= f.text_field :phone %></td>
  </div>
  </tr>
  </table>
  <div class="actions">
    <%= f.submit 'добавить'%>
  </div>
<% end %>

app/views/manufacturs/edit.html.erb
<h3>изменить данные</h3>

<%= render 'form' %>

<%= link_to 'показать', @manufactur %> |
<%= link_to 'назад', manufacturs_path %>

app/views/manufacturs/index.html.erb
<h2>Изготовители</h2>

<table>
  <tr>
    <th>название</th>
    <th>адрес</th>
    <th>телефон</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @manufacturs.each do |manufactur| %>
  <tr>
    <td><%= manufactur.name %></td>
    <td><%= manufactur.address %></td>
    <td><%= manufactur.phone %></td>
    <td><%= link_to 'просмотреть', manufactur %></td>
    <td><%= link_to 'изменить', edit_manufactur_path(manufactur) %></td>
    <td><%= link_to 'удалить', manufactur, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'добавить', new_manufactur_path %>
<%= link_to 'назад', guide_index_path %>

app/views/manufacturs/new.html.erb
<h3>введите данные нового изготовителя</h3>

<%= render 'form' %>  
<%= button_to 'назад', manufacturs_path %>

app/views/manufacturs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>название:</b>
  <%= @manufactur.name %>
</p>

<p>
  <b>адрес:</b>
  <%= @manufactur.address %>
</p>

<p>
  <b>телефон:</b>
  <%= @manufactur.phone %>
</p>


<%= link_to 'изменить', edit_manufactur_path(@manufactur) %> |
<%= link_to 'назад', manufacturs_path %>