config/routes.rb
Lkksswin::Application.routes.draw do

  get "report_gazcontrols/show"
  resources :report_gazcontrols

  get "report_controls/show"
  resources :report_controls

  get "costs/end_price"

  resources :cost_inputs

  resources :cost_menus

  resources :xls

  resources :menu_reports

  devise_for :users

  devise_for :models
  match '/certificates/new' => 'certificates#new'
  resources :costs
  post "certificates/cost"
  post "loadcertifics/new"
  post "data_pipes/new"
  resources :magazines
  get "magazines/show"
  get "journal/index"
  post "journal/index"
  get "journal/link"
  resources :type_pipe_installation_sites
  post "loadcertifics/download"
  post "loadcertifics/undownload"
  get "loadcertifics/download"
  get "loadcertifics/undownload"
  resources :loadcertifics
  get "load/index"
  get "load/rem"
  get "downloads/rem"
  resources :reports
  resources :results
  resources :support_documents
  resources :certificates
  resources :passports
  resources :passport_pipes
  resources :pipes
  resources :installation_sites
  resources :conclusions
  resources :data_pipes
  resources :type_pipes
  resources :documents
  resources :sizes_pipes
  resources :instrumentations
  resources :represent_trans
  resources :represent_hosts
  resources :ties
  resources :gosts
  resources :delegates
  resources :manufacturs
  get "guide/index"
  get "main/index"
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'loadcertifics#new'

end

app/models/akt.rb
class Akt < ActiveRecord::Base
  belongs_to :zavod
  belongs_to :tipdef
  belongs_to :ntrub
  belongs_to :konstr  
end

app/models/certificate.rb
class Certificate < ActiveRecord::Base
  belongs_to :sizes_pipe
  belongs_to :manufactur
  belongs_to :conclusion
  has_many :results,  :dependent => :delete_all
  belongs_to :installation_site
  belongs_to :gost
  belongs_to :ty
  belongs_to :support_document
  belongs_to :represent_host
  belongs_to :represent_tran
  belongs_to :instrumentation
  belongs_to :delegate
  belongs_to :type_pipe

end

app/models/cost.rb
class Cost < ActiveRecord::Base
end

app/models/cost_menu.rb
class CostMenu < ActiveRecord::Base
end

app/models/delegate.rb
class Delegate < ActiveRecord::Base
  has_many :certificates
end

app/models/document.rb
class Document < ActiveRecord::Base
  has_many :sizes_pipes
  has_many :conclusion
end

app/models/download.rb
class Download < ActiveRecord::Base
  attr_accessible :name, :link, :remote_link_url
  mount_uploader :link, LinkUploader
end

app/models/gost.rb
class Gost < ActiveRecord::Base
  has_many :certificates
end

app/models/konstr.rb
class Konstr < ActiveRecord::Base
  has_many :akts
end

app/models/magazine.rb
class Magazine < ActiveRecord::Base
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/ntrub.rb
class Ntrub < ActiveRecord::Base
  has_many :akts
end

app/models/passport.rb
class Passport < ActiveRecord::Base
  has_many :pipes, :through => :passport_pipes
end

app/models/pipe.rb
class Pipe < ActiveRecord::Base
  has_many :passports, :through => :passport_pipes
  belongs_to :data_pipe
  belongs_to :result
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :certificate
  belongs_to :pipe, :dependent => :delete
end

app/models/terra.rb
class Terra < ActiveRecord::Base
end

app/models/tipdef.rb
class Tipdef < ActiveRecord::Base
  has_many :akts
end

app/models/ty.rb
class Ty < ActiveRecord::Base
  has_many :certificates
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/xl.rb
class Xl < ActiveRecord::Base
end

app/models/zavod.rb
class Zavod < ActiveRecord::Base
  has_many :akts
end

app/controllers/certificates_controller.rb
class CertificatesController < InheritedResources::Base
  #before_filter :authenticate_user! #, :except => [:show, :index]
  def cost
    #$der = $length.nil? ? "123456" : $length.length
    $length = []
    @hour = CostInput.find(1).hour
    @material = CostInput.find(1).material
    @work = 0.01
    @sum = 0

    Result.find_all_by_certificate_id($idr).each do |rem|
      if rem.length.nil? or (rem.length == 0)
        len = 1
      else
        len = rem.length
      end
      if rem.width.nil? or (rem.width == 0)
        wid = 1
      else
        wid = rem.width
      end
      @s = wid * len
      @m = @s * @material
      @t = @s * @work
      @o = @t * @material
      @z = @m + @o
      @sum += @z
    end
    $der = @sum

    @certificate = Certificate.find($idr)
    @certificate.cost = @sum
    @certificate.save
    #respond_to do |format|
    #  if @certificate.update_attributes(params[:certificate])
    #    format.html { redirect_to @xl, notice: 'Xl was successfully updated.' }
    #    format.json { head :ok }
    #  else
    #    format.html { render action: "edit" }
    #    format.json { render json: @xl.errors, status: :unprocessable_entity }
    #  end
    #end



  end
  def show
    @certificate = Certificate.find(params[:id])
    $idr = @certificate.id
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @certificate }
    end
  end
  def create
    #@certificate = User.new(params[:certificate])
    #if @user.save
    #  sign_in @user
    #  flash[:success] = "Welcome to University Sports!"
    #  redirect_to @user
    #else
    #  @title = "Sign up"
    #  render 'new'
    #end
    redirect_to :action => 'new', :controller => 'data_pipes'
  end

end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/views/certificates/_form.html.erb
<%= form_for(@certificate) do |f| %>
  <% if @certificate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@certificate.errors.count, "error") %> prohibited this certificate from being saved:</h2>

      <ul>
      <% @certificate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <table BORDER=2  CELLPADDING=5>
      <tr>
        <td width="25%"><p align="right">тип акта</p></td>
        <td width="25%"> <%= f.text_field :name %></td>
        <td width="25%"></td>
        <td width="25%"></td>
      </tr>
      <tr>
        <td width="25%"><p align="right">№  <%= f.text_field :number %> </p></td>
        <td colspan="3"><p> от <%= f.date_select :date_issue%></p></td>
      </tr>
      <tr>
        <td>Место проведения входного контроля труб</td>
        <td><%= f.collection_select :installation_site_id, InstallationSite.all, :id, :object %></td>
        <td><p align="right">Трубы размером </p></td>
        <td><%= f.text_field :number %> </td>
      </tr>
      <tr>
        <td width="25%"><p align="right">Изготовлены по (ТУ, ГОСТ)</p></td>
        <td width="25%"><%= f.collection_select :gost_id, Gost.all, :id, :name %></td>
        <td width="25%"><p align="right">Конструкция труб</p></td>
        <td><%= f.collection_select :type_pipe_id, TypePipe.all, :id, :name %></td>
      </tr>
      <tr>
        <td width="25%"></td>
        <td width="25%"></td>
        <td width="25%"><p align="right">Класс прочности</p></td>
        <td><%= f.text_field :number %></td>
      </tr>
      <tr>
        <td width="25%"><p align="right">Изоляционное покрытие по ТУ</p></td>
        <td width="25%"><%= f.collection_select :ty_id, Ty.all, :id, :name %></td>
        <td width="25%"><p align="right">Завод изготовитель</p></td>
        <td width="25%"><p align="left"><%= f.collection_select :manufactur_id, Manufactur.all, :id, :name  %></p></td>
      </tr>
    </table>


  <div class="actions">
    <% f.submit 'продолжить заполение' %>

  </div>
    <%= button_to 'продолжить', :action => 'new', :controller => 'data_pipes' %>
<% end %>

app/views/certificates/cost.html.erb
стоимость работ составит =>   <%= @sum %>
<br>
<br>
<%= link_to 'вернутся к списку', :action => 'index', :controller => 'certificates' %>

app/views/certificates/edit.html.erb
<h1>Editing certificate</h1>

<%= render 'form' %>

<%= link_to 'Show', @certificate %> |
<%= link_to 'Back', certificates_path %>

app/views/certificates/index.html.erb
<h2>Акты входного контроля и освидетельствования</h2>
<br>
<%= form_for "$search" do |s| %>

   <div class="field">
       <%= s.label :search, t("введите ключевой слово для поиска") %>
       <%= s.text_field :search %> </p>
   </div>
   <table><tr>
   <div class="field">
        <td width="20"><%= s.label "произвести фильтрацию по"%></td>
        <td width="20"><%= s.collection_select :guide, Manufactur.all, :id, :phone %></td>
   </div>
   </tr>
   <tr>
   <div class="field">
        <td><%= s.label "и значению"%></td>
        <td><%= s.collection_select :guide, Manufactur.all, :id, :phone %></td>
   </div>
   </tr>
   </table>
<% end %>
<table>
<tr>
    <td width="5%"> <%= button_to 'поиск', :action => 'new', :controller => 'loadcertifics' %></td>
    <td width="5%"><%= button_to 'фильтрация', :action => 'new', :controller => 'loadcertifics' %></td>
    <td width="90%"></td>
</tr>
</table>
<h3>Cписок</h3>
<table class="table table-bordered">
  <tr>
    <th>Дата проведения контроля</th>
    <th>Название</th>
    <th>Номер</th>
    <th>Ремонт</th>
    <th>Действия</th>
  </tr>

<% @certificates.each do |certificate| %>
  <tr>
    <td><%= certificate.date_issue %></td>
    <td><%= certificate.name %></td>
    <td><%= certificate.number %></td>
    <td><%= certificate.cost %></td>
    <td>
    <%= link_to 'просмотреть', certificate, :class => "btn btn-mini btn-primary" %>
    <%= link_to 'изменить', edit_certificate_path(certificate), :class => "btn btn-mini btn-primary" %>
    <%= link_to 'удалить', certificate, confirm: 'Are you sure?', method: :delete, :class => "btn btn-mini btn-danger" %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= button_to 'добавить акт', new_certificate_path %>

app/views/certificates/new.html.erb
<h3>Новый акт</h3>

<%= render 'form' %>

<%= link_to '', certificates_path %>

app/views/certificates/show.html.erb
<p id="notice"><%= notice %></p>

<% if !@certificate.name.include?("(") %>
<table BORDER=2  CELLPADDING=5>
  <tr>
    <td width="30%"></td>
    <td width="40%"><p align="center"><%= @certificate.name %></p></td>
    <td width="30%"></td>
  </tr>
  <tr>
    <td width="30%"></td>
    <td width="40%"><p align="center">№  <%= @certificate.number %>  от <%= @certificate.date_issue%></p></td>
    <td width="30%"></td>
  </tr>
  <tr>
    <td width="30%"><p>Место проведения входного контроля труб</p></td>
    <td width="40%"><p align="center"><%= InstallationSite.find(@certificate.installation_site_id).object %></p></td>
    <td width="30%"><p>Трубы размером  <%= SizesPipe.find(@certificate.sizes_pipe_id).diameter_trunk %></p></td>
  </tr>
</table>
<table>
  <tr>
    <td width="25%">Изготовлены по (ТУ, ГОСТ)</td>
    <td width="25%"><p><%= Gost.find(@certificate.gost_id).name %></p></td>
    <td width="25%"><p>Конструкция труб    <%= TypePipe.find(@certificate.type_pipe_id).name %></p></td>
    <td width="25%"><p>Класс прочности    <%= SizesPipe.find(@certificate.sizes_pipe_id).strength_class %></p></td>
  </tr>
  <tr>
    <td width="25%">Изоляционное покрытие по ТУ</td>
    <td width="25%"><p align="left"><%= Ty.find(@certificate.ty_id).name %></p></td>
    <td width="25%"><p>Завод изготовитель    </p></td>
    <td width="25%"><p align="left"><%= Manufactur.find(@certificate.manufactur_id).name %></p></td>
  </tr>
</table>
<table >
  <tr  ROWSPAN="2">
    <td width="2%" rowspan="2"><p align="center">№ п/п</p></td>
    <td width="7%" rowspan="2"><p align="center">Присвоен. № трубы/ партии/ плавки</p></td>
    <td width="7%" rowspan="2"><p align="center">№ сертиф.</p></td>
    <td width="8%" rowspan="2"><p align="center">Дата отгрузки</p></td>
    <td width="8%" rowspan="2"><p align="center">Дата нанисения изол.</p></td>
    <td width="5%" rowspan="2"><p align="center">Фактич. диам. мм</p></td>
    <td width="3%" rowspan="2"><p align="center">Овальность, мм</p></td>
    <td width="3%" rowspan="2"><p align="center">Длина, м</p></td>
    <td width="4%" rowspan="2"><p align="center">Толщина стенки, мм</p></td>
    <td width="43%" colspan="6"><p align="center">Описание дефектов</p></td>
    <td width="4%" rowspan="2"><p align="center">Ост. Маг. инд. мТс</p></td>
    <td width="4%" rowspan="2"><p align="center">Отметка о годности</p></td>
  </tr>
  <tr>
    <td><p align="center">Тип дефекта</p></td>
    <td><p align="center">От марк. торца, м</p></td>
    <td><p align="center">Длина, мм</p></td>
    <td><p align="center">Ширина, мм</p></td>
    <td><p align="center">Глубина, мм</p></td>
    <td><p align="center">Ост. толщина, мм</p></td>
  </tr>
  <tr>
    <% for @i in 1..17 %>
        <td ><p align="center"><%= @i %></p></td>
    <% end %>
  </tr>
  <% Result.find_all_by_certificate_id(@certificate.id).each do |rem|  %>
    <tr>
        <td width="2%"><p align="center"><%=  %></p></td>
        <td width="7%"><p align="center"><%= Pipe.find(rem.pipe_id).notation%>/<br> <%= DataPipe.find(Pipe.find(rem.pipe_id).data_pipe_id).number_product %>/<br><%= %></p></td>
        <td width="7%"><p align="center"><%= DataPipe.find(Pipe.find(rem.pipe_id).data_pipe_id).certific %></p></td>
        <td width="8%"><p align="center"><%= rem.date_issue %></p></td>
        <td width="8%"><p align="center"><%= rem.application_isolation%></p></td>
        <td width="5%"><p align="center">марк.<br><%= rem.outside_diameter.split("/")[0] %><br>немарк.<br><%= rem.outside_diameter.split("/")[1] %></p></td>
        <td width="3%"><p align="center"><br><%= rem.roundness.split("/")[0] %><br><br><%= rem.roundness.split("/")[1] %></p></td>
        <td width="3%"><p align="center"><%= rem.length_all  %></p></td>
        <td width="4%"><p align="center"><%= rem.wall_tickness.split("/")[0] %><br><%= rem.wall_tickness.split("/")[1] %><br><%= rem.wall_tickness.split("/")[2] %><br><%= rem.wall_tickness.split("/")[3] %></p></td>
        <td width="13%"><p align="center"><%= rem.type_def %></p></td>
        <td width="5%"><p align="center"><%= rem.from_mark_butt %></p></td>
        <td width="5%"><p align="center"><%= rem.length %></p></td>
        <td width="5%"><p align="center"><%= rem.width %></p></td>
        <td width="7%"><p align="center"><%= rem.deep %></p></td>
        <td width="7%"><p align="center"><%= rem.thickness %></p></td>
        <td width="4%"><p align="center"><%= rem.magnet.split("/")[0] %><br><%= rem.magnet.split("/")[1] %><br><%= rem.magnet.split("/")[2] %><br><%= rem.magnet.split("/")[3] %></p></td>
        <td width="4%"><p align="center"><%= rem.mark_date %></p></td>
     </tr>
  <% end %>
</table>
    Примечание: в ст.  6-17 записывают фактические результаты измерений.<br>
    Используемые приборы и измерительный инструмент:<%= Instrumentation.find(@certificate.instrumentation_id).name %> <br>
    Акт составлен на <% $list %>  лист., прилагаются копии сертификатов качества.<br>
    Заключение<p align="center"> <%= Conclusion.find(@certificate.conclusion_id).output %></p>
    <table>
            <tr>
              <td width="25%"><p>Контроль произведен в присутствии:</p></td>
              <td width="25%"><p align="center"><%= RepresentHost.find(@certificate.represent_host_id).last_name %></p></td>
              <td width="25%"><p align="center"><%= RepresentHost.find(@certificate.represent_host_id).job %></p></td>
              <td width="14%"><p align="center"></p></td>
              <td width="11%"><p align="right"><% $date1 %></p></td>
            </tr>
            <tr>
              <td width="25%"><p>Провел контроль с выдачей заключения:</p></td>
              <td width="25%"><p align="center"><%= Delegate.find(@certificate.delegate_id).last_name %></p></td>
              <td width="25%"><p align="center"><%= Delegate.find(@certificate.delegate_id).level_nk %></p></td>
              <td width="14%"><p align="center"></p></td>
              <td width="11%"><p align="right"><% $date2 %></p></td>
            </tr>
            <tr>
              <td width="25%"><p>С результатом ознакомлен, акт выдан:</p></td>
              <td width="25%"><p align="center"><%= RepresentTran.find(@certificate.represent_trans_id).last_name %></p></td>
              <td width="25%"><p align="center"><%= RepresentTran.find(@certificate.represent_trans_id).job %></p></td>
              <td width="14%"><p align="center"></p></td>
              <td width="11%"><p align="right"><% $date3 %></p></td>
            </tr>
    </table>

<% else %>
    <table BORDER=2  CELLPADDING=5>
      <tr>
        <td width="30%"></td>
        <td width="40%"><p align="center"><%= @certificate.name %></p></td>
        <td width="30%"></td>
      </tr>
      <tr>
        <td width="30%"></td>
        <td width="40%"><p align="center">№  <%= @certificate.number %>  от <%= @certificate.date_issue%></p></td>
        <td width="30%"></td>
      </tr>
      <tr>
        <td width="30%"><p>Место проведения входного контроля труб</p></td>
        <td width="40%"><p align="center"><%= InstallationSite.find(@certificate.installation_site_id).object %></p></td>
        <td width="30%"><p>Трубы размером  <%= SizesPipe.find(@certificate.sizes_pipe_id).diameter_trunk %></p></td>
      </tr>
    </table>
    <table>
      <tr>
        <td width="25%">Изготовлены по (ТУ, ГОСТ)</td>
        <td width="25%"><p><%= Gost.find(@certificate.gost_id).name %></p></td>
        <td width="25%"><p>Конструкция труб    <%= TypePipe.find(@certificate.type_pipe_id).name %></p></td>
        <td width="25%"><p>Класс прочности    <%= SizesPipe.find(@certificate.sizes_pipe_id).strength_class %></p></td>
      </tr>
      <tr>
        <td width="25%">Изоляционное покрытие по ТУ</td>
        <td width="25%"><p align="left"><%= Ty.find(@certificate.ty_id).name %></p></td>
        <td width="25%"><p>Завод изготовитель    </p></td>
        <td width="25%"><p align="left"><%= Manufactur.find(@certificate.manufactur_id).name %></p></td>
      </tr>
    </table>
    <table >
      <tr  ROWSPAN="2">
        <td width="2%" rowspan="2"><p align="center">№ п/п</p></td>
        <td width="7%" rowspan="2"><p align="center">Присвоен. № трубы/ партии/ плавки</p></td>
        <td width="7%" rowspan="2"><p align="center">№ сертиф.</p></td>
        <td width="8%" rowspan="2"><p align="center">Дата отгрузки</p></td>
        <td width="8%" rowspan="2"><p align="center">Дата нанисения изол.</p></td>
        <td width="5%" rowspan="2"><p align="center">Фактич. диам. мм</p></td>
        <td width="3%" rowspan="2"><p align="center">Овальность, мм</p></td>
        <td width="3%" rowspan="2"><p align="center">Длина, м</p></td>
        <td width="4%" rowspan="2"><p align="center">Толщина стенки, мм</p></td>
        <td width="43%" colspan="7"><p align="center">Описание дефектов</p></td>
        <td width="4%" rowspan="2"><p align="center">Ост. Маг. инд. мТс</p></td>
        <td width="4%" rowspan="2"><p align="center">Отметка о годности</p></td>
      </tr>
      <tr>
        <td><p align="center">Тип дефекта</p></td>
        <td><p align="center">От марк. торца, м</p></td>
        <td><p align="center">От пр. шва м</p></td>
        <td><p align="center">Длина, мм</p></td>
        <td><p align="center">Ширина, мм</p></td>
        <td><p align="center">Глубина, мм</p></td>
        <td><p align="center">Ост. толщина, мм</p></td>
      </tr>
      <tr>
        <% for @i in 1..18 %>
            <td ><p align="center"><%= @i %></p></td>
        <% end %>
      </tr>
      <% Result.find_all_by_certificate_id(@certificate.id).each do |rem|  %>
        <tr>
            <td width="2%"><p align="center"><%=  %></p></td>
            <td width="7%"><p align="center"><%= Pipe.find(rem.pipe_id).notation%>/<br> <%= DataPipe.find(Pipe.find(rem.pipe_id).data_pipe_id).number_product %>/<br><%= %></p></td>
            <td width="7%"><p align="center"><%= DataPipe.find(Pipe.find(rem.pipe_id).data_pipe_id).certific %></p></td>
            <td width="8%"><p align="center"><%= rem.date_issue %></p></td>
            <td width="8%"><p align="center"><%= rem.application_isolation%></p></td>
            <td width="5%"><p align="center">марк.<br><%= rem.outside_diameter.split("/")[0] %><br>немарк.<br><%= rem.outside_diameter.split("/")[1] %></p></td>
            <td width="3%"><p align="center"><br><%= rem.roundness.split("/")[0] %><br><br><%= rem.roundness.split("/")[1] %></p></td>
            <td width="3%"><p align="center"><%= rem.length_all  %></p></td>
            <td width="4%"><p align="center"><%= rem.wall_tickness.split("/")[0] %><br><%= rem.wall_tickness.split("/")[1] %><br><%= rem.wall_tickness.split("/")[2] %><br><%= rem.wall_tickness.split("/")[3] %></p></td>
            <td width="13%"><p align="center"><%= rem.type_def %></p></td>
            <td width="5%"><p align="center"><%= rem.from_mark_butt %></p></td>
            <td width="5%"><p align="center"><%= rem.length %></p></td>
            <td width="5%"><p align="center"><%= rem.from_right_seam %></p></td>
            <td width="5%"><p align="center"><%= rem.width %></p></td>
            <td width="7%"><p align="center"><%= rem.deep %></p></td>
            <td width="7%"><p align="center"><%= rem.thickness %></p></td>
            <td width="4%"><p align="center"><%= rem.magnet.split("/")[0] %><br><%= rem.magnet.split("/")[1] %><br><%= rem.magnet.split("/")[2] %><br><%= rem.magnet.split("/")[3] %></p></td>
            <td width="4%"><p align="center"><%= rem.mark_date %></p></td>
         </tr>
      <% end %>
    </table>
    Примечание: в ст.  6-17 записывают фактические результаты измерений.<br>
    Используемые приборы и измерительный инструмент:<%= Instrumentation.find(@certificate.instrumentation_id).name %> <br>
    Акт составлен на <% $list %>  лист., прилагаются копии сертификатов качества.<br>
    Заключение<p align="center"> <%= Conclusion.find(@certificate.conclusion_id).output %></p>
    <table>
            <tr>
              <td width="25%"><p>Контроль произведен в присутствии:</p></td>
              <td width="25%"><p align="center"><%= RepresentHost.find(@certificate.represent_host_id).last_name %></p></td>
              <td width="25%"><p align="center"><%= RepresentHost.find(@certificate.represent_host_id).job %></p></td>
              <td width="14%"><p align="center"></p></td>
              <td width="11%"><p align="right"><% $date1 %></p></td>
            </tr>
            <tr>
              <td width="25%"><p>Провел контроль с выдачей заключения:</p></td>
              <td width="25%"><p align="center"><%= Delegate.find(@certificate.delegate_id).last_name %></p></td>
              <td width="25%"><p align="center"><%= Delegate.find(@certificate.delegate_id).job %></p></td>
              <td width="14%"><p align="center"></p></td>
              <td width="11%"><p align="right"><% $date2 %></p></td>
            </tr>
            <tr>
              <td width="25%"><p>С результатом ознакомлен, акт выдан:</p></td>
              <td width="25%"><p align="center"><%= RepresentTran.find(@certificate.represent_trans_id).last_name %></p></td>
              <td width="25%"><p align="center"><%= RepresentTran.find(@certificate.represent_trans_id).job %></p></td>
              <td width="14%"><p align="center"></p></td>
              <td width="11%"><p align="right"><% $date3 %></p></td>
            </tr>
    </table>
<% end  %>
<br>

<% $fed=1000 %>

<%= button_to 'произвести расчет затрат', :action => 'cost', :controller => 'certificates' %>
<% link_to 'изменить', edit_certificate_path(@certificate) %>
<%= button_to 'назад', certificates_path %>